# **4.1 Exercise on Functions**

# **Task1**

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.


• Conversion Options:
1. Length:

    – Convert meters (m) to feet (ft).

    – Convert feet (ft) to meters (m).

2. Weight:


    – Convert kilograms (kg) to pounds (lbs).

    – Convert pounds (lbs) to kilograms (kg).

3. Volume:


    – Convert liters (L) to gallons (gal).

    – Convert gallons (gal) to liters (L).

In [1]:
def convert_units(category, value, choice):
    """
    Convert units based on category and choice.

    category: length / weight / volume
    value: number to convert
    choice: "1" or "2"
    returns: converted number
    """
    if category == "length":
        if choice == "1":      # meters -> feet
            return value * 3.28084
        elif choice == "2":    # feet -> meters
            return value / 3.28084

    elif category == "weight":
        if choice == "1":      # kg -> pounds
            return value * 2.20462
        elif choice == "2":    # pounds -> kg
            return value / 2.20462

    elif category == "volume":
        if choice == "1":      # liters -> gallons
            return value * 0.264172
        elif choice == "2":    # gallons -> liters
            return value / 0.264172

    raise ValueError("Invalid choice.")


def unit_converter():
    """
    Ask user for conversion type and value, then print the result.
    Handles invalid category, invalid number input, and wrong choice.
    """
    print("Choose category: length / weight / volume")
    category = input("Category: ").lower().strip()

    # check category to ensure its there
    if category not in ["length", "weight", "volume"]:
        print("Invalid category.")
        return

    try:
        value = float(input("Enter value: "))
    except ValueError:
        print("Invalid input! Please enter a number.")
        return

    if category == "length":
        print("1 = meters to feet")
        print("2 = feet to meters")
    elif category == "weight":
        print("1 = kg to pounds")
        print("2 = pounds to kg")
    elif category == "volume":
        print("1 = liters to gallons")
        print("2 = gallons to liters")

    choice = input("Choose 1 or 2: ").strip()

    try:
        result = convert_units(category, value, choice)
    except ValueError as e:
        print("Error:", e)
        return

    # Display result
    if category == "length" and choice == "1":
        print("Feet =", result)
    elif category == "length" and choice == "2":
        print("Meters =", result)
    elif category == "weight" and choice == "1":
        print("Pounds =", result)
    elif category == "weight" and choice == "2":
        print("Kg =", result)
    elif category == "volume" and choice == "1":
        print("Gallons =", result)
    elif category == "volume" and choice == "2":
        print("Liters =", result)


unit_converter()


Choose category: length / weight / volume
Category: WEIGHT
Enter value: 45
1 = kg to pounds
2 = pounds to kg
Choose 1 or 2: 1
Pounds = 99.2079


# ***Task-2***

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.


• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.


In [2]:
def sum_numbers(nums):
    """Return the sum of a list of numbers."""
    total = 0
    for x in nums:
        total += x
    return total

def average_numbers(nums):
    """Return the average of a list of numbers."""
    if len(nums) == 0:
        raise ValueError("Empty list")
    return sum_numbers(nums) / len(nums)

def max_number(nums):
    """Return the maximum value in a list of numbers."""
    if len(nums) == 0:
        raise ValueError("Empty list")
    m = nums[0]
    for x in nums:
        if x > m:
            m = x
    return m

def min_number(nums):
    """Return the minimum value in a list of numbers."""
    if len(nums) == 0:
        raise ValueError("Empty list")
    m = nums[0]
    for x in nums:
        if x < m:
            m = x
    return m

def list_math_program():
    """Ask user for an operation and numbers, then print the result."""
    print("Choose operation: sum / avg / max / min")
    op = input("Operation: ").lower().strip()

    if op not in ["sum", "avg", "max", "min"]:
        print("Invalid operation.")
        return

    try:
        parts = input("Enter numbers separated by spaces: ").split()
        if len(parts) == 0:
            print("Empty list!")
            return
        nums = [float(x) for x in parts]
    except ValueError:
        print("Invalid input! Please enter only numbers.")
        return

    if op == "sum":
        print("Sum =", sum_numbers(nums))
    elif op == "avg":
        print("Average =", average_numbers(nums))
    elif op == "max":
        print("Max =", max_number(nums))
    elif op == "min":
        print("Min =", min_number(nums))

list_math_program()

Choose operation: sum / avg / max / min
Operation: SUM
Enter numbers separated by spaces: 1 2 3 4
Sum = 10.0


# **4.2 Exercise on List manipulation**


**1. Extract Every Other Element:**

    Write a Python function that extracts every other element from a list, starting from the first element.


*• Requirements:*

    – Define a function extract every other(lst) that takes a list lst as input and returns a
    new list containing every other element from the original list.


    – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [3]:
def extract_every_other(lst):
    """Return every other element starting from the first."""
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


**2. Slice a Sublist:**

    Write a Python function that returns a sublist from a given list, starting from a specified index and
    ending at another specified index.

*• Requirements:*

    – Define a function get sublist(lst, start, end) that takes a list lst, a starting index
    start, and an ending index end as input and returns the sublist from start to end (inclusive).

    – Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
    be [3, 4, 5].

In [4]:
def get_sublist(lst, start, end):
    """Return sublist from start to end (inclusive)."""
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


**3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.

*• Requirements:*

    – Define a function reverse list(lst) that takes a list lst and returns a reversed list using
    slicing.

    – Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [5]:
def reverse_list(lst):
    """Return the list reversed using slicing."""
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

*• Requirements:*

    – Define a function remove first last(lst) that takes a list lst and returns a sublist without
    the first and last elements using slicing.

    – Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [6]:
def remove_first_last(lst):
    """Return list without the first and last elements."""
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


**5. Get the First n Elements:**

Write a Python function that extracts the first n elements from a list.

*• Requirements:*

    – Define a function get first n(lst, n) that takes a list lst and an integer n as input and
    returns the first n elements of the list using slicing.

    – Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [7]:
def get_first_n(lst, n):
    """Return the first n elements of the list."""
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 2))

[1, 2]


**6. Extract Elements from the End:**

Write a Python function that extracts the last n elements of a list using slicing.

*• Requirements:*

    – Define a function get last n(lst, n) that takes a list lst and an integer n as input and
    returns the last n elements of the list.

    – Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [8]:
def get_last_n(lst, n):
    """Return the last n elements of the list."""
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 4))

[2, 3, 4, 5]


**7. Extract Elements in Reverse Order:**

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

*• Requirements:*

    – Define a function reverse skip(lst) that takes a list lst and returns a new list containing
    every second element starting from the second-to-last, moving backward.

    – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [9]:
def reverse_skip(lst):
    """Return every second element from the second-to-last going backwards."""
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


# **4.3 Exercise on Nested List:**

**1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

*• Requirements:*

    – Define a function flatten(lst) that takes a nested list lst and returns a flattened version
    of the list.

    – Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [10]:
def flatten(lst):
    """Flatten a list of lists into one list (one level)."""
    out = []
    for sub in lst:
        for item in sub:
            out.append(item)
    return out

print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.

*• Requirements:*

    – Define a function access nested element(lst, indices) that takes a nested list lst and
    a list of indices indices, and returns the element at that position.

    – Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
    2], the output should be 6.

In [11]:
def access_nested_element(lst, indices):
    """Return element from nested list using a list of indices."""
    current = lst
    for idx in indices:
        current = current[idx]
    return current

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(lst, [1, 2]))

6


**3. Sum of All Elements in a Nested List:**

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements: *italicized text*

    – Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
    the elements.

    – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [12]:
def sum_nested(lst):
    """Return sum of all numbers in a nested list."""
    total = 0
    for item in lst:
        if type(item) == list:
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


**4. Remove Specific Element from a Nested List:**

Write a Python function that removes all occurrences of a specific element from a nested list.

*• Requirements:*

    – Define a function remove element(lst, elem) that removes elem from lst and returns the
    modified list.

    – Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
    be [[1], [3], [4, 5]].

In [13]:
def remove_element(lst, elem):
    """Remove all occurrences of elements from nested list (any depth)."""
    out = []
    for item in lst:
        if type(item) == list:
            out.append(remove_element(item, elem))
        else:
            if item != elem:
                out.append(item)
    return out

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))

[[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List:**

Write a Python function that finds the maximum element in a nested list (regardless of depth).

*• Requirements:*

    – Define a function find max(lst) that takes a nested list lst and returns the maximum
    element.

    – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [14]:
def find_max(lst):
    """Return the maximum element in a nested list (any depth)."""
    current_max = None
    for item in lst:
        if type(item) == list:
            val = find_max(item)
        else:
            val = item

        if current_max is None or val > current_max:
            current_max = val
    return current_max

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


**6. Count Occurrences of an Element in a Nested List:**

Write a Python function that counts how many times a specific element appears in a nested list.

*• Requirements:*

    – Define a function count occurrences(lst, elem) that counts the occurrences of elem in
    the nested list lst.

    – Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
    be 3.

In [15]:
def count_occurrences(lst, elem):
    """Count how many times elements appears in nested list (any depth)."""
    count = 0
    for item in lst:
        if type(item) == list:
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

3


**7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

*• Requirements:*

    – Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
    flattened list.

    – Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
    [1, 2, 3, 4, 5, 6, 7, 8].

In [16]:
def deep_flatten(lst):
    """Flatten a nested list of any depth into one list."""
    out = []
    for item in lst:
        if type(item) == list:
            out.extend(deep_flatten(item))
        else:
            out.append(item)
    return out

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.

*• Requirements:*

    – Define a function average nested(lst) that takes a nested list lst and returns the average
    of all the elements.

    – Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [17]:
def average_nested(lst):
    """Return average of all numbers in nested list (any depth)."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print(average_nested([[1, 2], [3, 4], [5, 6]]))  # 3.5

3.5


# **10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

Complete the following Tasks:

**1. Initialize an empty array with size 2X2.**


In [18]:
# Necessary import
import numpy as np

arr1 = np.empty((2, 2))
print("1. Empty 2x2:\n", arr1)

1. Empty 2x2:
 [[6.79411078e-310 4.94512914e-315]
 [6.79410955e-310 6.79408301e-310]]


**2. Initialize an all one array with size 4X2.**

In [19]:
arr2 = np.ones((4, 2))
print("2.Ones 4x2:\n", arr2)

2.Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}**

In [20]:
arr3 = np.full((3, 4), 8)
print("3. Full 3x4 with 8:\n", arr3)

3. Full 3x4 with 8:
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


**4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}**

In [21]:
given = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr4 = np.zeros_like(given)
print("4. Zeros like given:\n", arr4)

4. Zeros like given:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


**5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}**

In [22]:
arr5 = np.ones_like(given)
print("5. Ones like given:\n", arr5)

5. Ones like given:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


**6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}**

In [23]:
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print("6. List to array:\n", arr6)

6. List to array:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:


**1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.**


In [24]:
arr1 = np.arange(10, 50)
print("1. 10 to 49:\n", arr1)

1. 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**2. Create a 3X3 matrix with values ranging from 0 to 8.**
{Hint:look for np.reshape()}

In [25]:
arr2 = np.arange(9).reshape(3, 3)
print("2. 3x3 (0 to 8):\n", arr2)

2. 3x3 (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**3. Create a 3X3 identity matrix.**{Hint:np.eye()}

In [26]:
arr3 = np.eye(3)
print("\n3) Identity 3x3:\n", arr3)


3) Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4. Create a random array of size 30 and find the mean of the array.**
{Hint:check for np.random.random() and array.mean() function}

In [27]:
arr4 = np.random.random(30)
print("4. Mean of random 30 =", arr4.mean())

4. Mean of random 30 = 0.4349311041704217


**5. Create a 10X10 array with random values and find the minimum and maximum values.**

In [28]:
arr5 = np.random.random((10, 10))
print("5. Min =", arr5.min())
print("5. Max =", arr5.max())

5. Min = 0.008004707151577528
5. Max = 0.9974987211529749


**6. Create a zero array of size 10 and replace 5th element with 1.**

In [29]:
arr6 = np.zeros(10)
arr6[4] = 1
print("6. Replace 5th element:\n", arr6)

6. Replace 5th element:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7. Reverse an array arr = [1,2,0,0,4,0].**

In [30]:
arr7 = np.array([1, 2, 0, 0, 4, 0])
print("7. Reversed:\n", arr7[::-1])

7. Reversed:
 [0 4 0 0 2 1]


**8. Create a 2d array with 1 on border and 0 inside.**

In [31]:
arr8 = np.ones((5, 5), dtype=int)
arr8[1:-1, 1:-1] = 0
print("8. Border 1 inside 0:\n", arr8)

8. Border 1 inside 0:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**9. Create a 8X8 matrix and fill it with a checkerboard pattern.**

In [32]:
arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("9. Checkerboard:\n", arr9)

9. Checkerboard:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Problem - 3: Array Operations:


For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

In [33]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

**1. Add the two array.**

In [34]:
add = x + y
print("1. Addition of x + y:\n", add)

1. Addition of x + y:
 [[ 6  8]
 [10 13]]


**2. Subtract the two array.**

In [35]:
sub = v - w
print("2. Substraction of v - w:\n", sub)

2. Substraction of v - w:
 [-2 -2]


**3. Multiply the array with any integers of your choice.**

In [36]:
mul = x * 4
print("3. Multiplication of x * 4:\n", mul)

3. Multiplication of x * 4:
 [[ 4  8]
 [12 20]]


**4. Find the square of each element of the array.**

In [37]:
squared  = y ** 2
print("4. y squared:\n", squared)

4. y squared:
 [[25 36]
 [49 64]]


**5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.**

In [38]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("5. v dot w =", dot_vw)
print("5. x dot v =", dot_xv)
print("5. x dot y:\n", dot_xy)

5. v dot w = 219
5. x dot v = [29 77]
5. x dot y:
 [[19 22]
 [50 58]]


**6. Concatenate x(and)y along row and Concatenate v(and)w along column.**
{Hint:try np.concatenate() or np.vstack() functions.

In [39]:
concat_xy_rows = np.concatenate((x, y), axis=0)
print("6. Concatenate x and y along rows:\n", concat_xy_rows)

concat_vw_cols = np.column_stack((v, w))
print("Concatenate v and w along columns:\n", concat_vw_cols)

6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


**7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?**

In [40]:
# np.concatenate((x, v), axis=0)   # ERROR

# This code gives an error because x is a 2D array and v is 1D array, therefore their dimesnions does not match so we cannot perform any operations on them.

# Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);


In [41]:
# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

Prove following with Numpy:

**1. Prove A.A−1 = I.**

In [42]:
A_inv = np.linalg.inv(A)
result_identity = A @ A_inv

print(np.round(result_identity))


[[1. 0.]
 [0. 1.]]


**2. Prove AB ̸= BA.**

In [43]:
AB = A @ B
BA = B @ A

print("2. AB:\n", AB)
print("2. BA:\n", BA)

if np.array_equal(AB, BA):
    print("2. AB equals BA")
else:
    print("2. AB does not equal BA")

2. AB:
 [[23 13]
 [51 29]]
2. BA:
 [[36 44]
 [13 16]]
2. AB does not equal BA


**3. Prove (AB)T = BT.AT**


In [44]:
left = (A @ B).T
right = B.T @ A.T

print("(AB)^T:\n", left)
print("B^T A^T:\n", right)

if np.array_equal(left, right):
    print("Proved: (AB)^T = B^T A^T")
else:
    print("Not equal")

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Proved: (AB)^T = B^T A^T


**• Solve the following system of Linear equation using Inverse Methods.**

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

**2x − 3y + z = −1**

**x − y + 2z = −3**

**3x + y − z = 9**

In [45]:
import numpy as np

A = np.array([[2, -3,  1],
              [1, -1,  2],
              [3,  1, -1]], dtype=float)

B = np.array([-1, -3, 9], dtype=float)

X = np.linalg.solve(A, B)

print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

x = 2.0
y = 1.0000000000000002
z = -2.0


Now: solve the above equation using np.linalg.inv function. {Explore more about ”linalg” function of Numpy}

In [46]:
#coefficients
A = np.array([[2, -3,  1],
              [1, -1,  2],
              [3,  1, -1]], dtype=float)

#constants
B = np.array([-1, -3, 9], dtype=float)

# Inverse method: X = inv(A) * B
X = np.linalg.inv(A) @ B

print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

x = 2.0
y = 1.0
z = -2.0


# 10.2 Experiment: How Fast is Numpy?


**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.


In [47]:
#Necessary Import
import time

#Size
N = 1_000_000

In [48]:
# Python Lists
a = list(range(N))
b = list(range(N, 2*N))

In [49]:
# NumPy Arrays
a_np = np.arange(N)
b_np = np.arange(N, 2*N)

In [50]:
start = time.perf_counter()
c = [a[i] + b[i] for i in range(N)]
end = time.perf_counter()
print("List addition time:", end - start, "seconds")


List addition time: 0.43565939600000547 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [51]:
start = time.perf_counter()
c_np = a_np + b_np
end = time.perf_counter()
print("NumPy addition time:", end - start, "seconds")

NumPy addition time: 0.007522056999988536 seconds


**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

In [52]:
start = time.perf_counter()
c = [a[i] * b[i] for i in range(N)]
end = time.perf_counter()
print("List multiplication time:", end - start, "seconds")


List multiplication time: 0.38246504800000025 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [53]:
start = time.perf_counter()
c_np = a_np * b_np
end = time.perf_counter()
print("NumPy multiplication time:", end - start, "seconds")

NumPy multiplication time: 0.017955631999996058 seconds


**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [54]:
start = time.perf_counter()
dot_list = sum(a[i] * b[i] for i in range(N))
end = time.perf_counter()
print("List dot product time:", end - start, "seconds")

List dot product time: 0.4757472889999974 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [55]:
start = time.perf_counter()
dot_np = np.dot(a_np, b_np)
end = time.perf_counter()
print("NumPy dot product time:", end - start, "seconds")

NumPy dot product time: 0.007284066999972083 seconds


**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [57]:
SIZE = 1000

# Python Lists
A = [list(range(SIZE)) for _ in range(SIZE)]
B = [list(range(SIZE)) for _ in range(SIZE)]

def list_matmul(A, B):
    result = [[0] * SIZE for _ in range(SIZE)]
    for i in range(SIZE):
        for k in range(SIZE):
            for j in range(SIZE):
                result[i][j] += A[i][k] * B[k][j]
    return result

start = time.perf_counter()
C = list_matmul(A, B)
end = time.perf_counter()
print("List matrix multiplication time:", end - start, "seconds")

List matrix multiplication time: 143.02580219599997 seconds


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [58]:
# NumPy Arrays
A_np = np.array(A, dtype=float)
B_np = np.array(B, dtype=float)

start = time.perf_counter()
C_np = A_np @ B_np
end = time.perf_counter()
print("NumPy matrix multiplication time:", end - start, "seconds")

NumPy matrix multiplication time: 0.06819013599999835 seconds
